/*************************************************************************
* ADOBE CONFIDENTIAL
* ___________________
*
*  Copyright 2015 Adobe Systems Incorporated
*  All Rights Reserved.
*
* NOTICE:  All information contained herein is, and remains
* the property of Adobe Systems Incorporated and its suppliers,
* if any.  The intellectual and technical concepts contained
* herein are proprietary to Adobe Systems Incorporated and its
* suppliers and are protected by all applicable intellectual property laws,
* including trade secret and or copyright laws.
* Dissemination of this information or reproduction of this material
* is strictly forbidden unless prior written permission is obtained
* from Adobe Systems Incorporated.
**************************************************************************/
import{dcLocalStorage as e}from"../../common/local-storage.js";import{loggingApi as a}from"../../common/loggingApi.js";import{getGenAIServiceVariant as t}from"../../common/util.js";import{util as r}from"../../browser/js/content-util.js";import{HOST_PAGE_TYPE as s}from"../../common/host-page-context.js";import{getSidePanelTabId as n,connectSidePanelPort as o}from"./sidePanelUtil.js";export class Cdn{urlParams=new URLSearchParams(window.location.search);tabId=n();iframeElement=document.getElementById("sidepanel");constructor({initTimeStamp:n,hostedHashRoute:i,touchpoint:m,anonGenAISSRHtml:p,hostPageType:d,onIframeLoad:h,onIframeError:c}){const l=new URL(e.getItem("sidepanelUrl"));l.hash=i;const g="true"===e.getItem("adobeInternal"),f="false"!==e.getItem("logAnalytics"),u="false"!==e.getItem("ANALYTICS_OPT_IN_ADMIN"),P=e.getItem("appLocale")||chrome.i18n.getMessage("@@ui_locale");l.searchParams.append("la",f&&u),l.searchParams.append("ca",chrome.runtime.id),l.searchParams.append("cluster",t()),l.searchParams.append("locale",P),l.searchParams.append("uuid",e.getItem("sidePanelUUID")),l.searchParams.append("adi",g),l.searchParams.append("its",n),l.searchParams.append("ev",this.urlParams.get("version")),l.searchParams.append("ecid",e.getItem("ECID")),l.searchParams.append("fabVariant",e.getItem("fabVariant")||""),l.searchParams.append("gaiuo",e.getItem("enableGenAIUnlimitedOffer")),l.searchParams.append("utl",!0),l.searchParams.append("uua",!!e.getItem("enableUUA")),l.searchParams.append("home",!!e.getItem("isSidePanelHomeEnabled")),l.searchParams.append("fgContextVars",JSON.stringify(e.getItem("fgContextVars")||{})),l.searchParams.append("hsnap",!!p),l.searchParams.append("slt",r.getTranslation("tooltipTextEnabled")),l.searchParams.append("hpt",d??s.DEFAULT),this.iframeElement.onload=()=>{a.info({message:"Hosted iframe loaded",url:this.iframeElement.src,touchpoint:m}),h?.()},this.iframeElement.onerror=e=>{a.error({message:"Error in loading hosted iframe",error:e.toString(),url:this.iframeElement.src,touchpoint:m}),c?.()},this.iframeElement.src=l.href,this.origin=l.origin,this.port=o(this.tabId,n)}isCdnReady=new Promise((e,a)=>{const t=setTimeout(()=>{a(new Error("Hosted shell ready event timeout"))},2e4);this.isCdnReadyResolver=()=>{clearTimeout(t),e()}});supportedOrigin=e=>{try{return!![/^https:\/\/([a-zA-Z\d-]+\.){0,}(adobe|acrobat)\.com(:[0-9]*)?$/].find(a=>a.test(e))}catch(e){return!1}};sendMessage=e=>{this.iframeElement&&this.supportedOrigin(this.origin)&&this.isCdnReady.then(()=>this.iframeElement.contentWindow.postMessage(e,this.origin)).catch(e=>{a.error({message:"Error in sending message to hosted shell",error:e.toString()})})}}